### ISSUE TITLE
Docker container not starting

### ISSUE THREAD

**Issue by engel75** [EmbarkStudios/wireguard-ui#11]
**Describe the bug**
Following your instractions to test the UI stating the docker container fails with message:

Error: container_linux.go:346: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": OCI runtime command not found error

I tested with podman and docker-ce

**Comment by jtc42** [comment]
I believe this is a duplicate of https://github.com/EmbarkStudios/wireguard-ui/issues/8

See https://github.com/EmbarkStudios/wireguard-ui/issues/8#issuecomment-544254043 for a possible solution

**Comment by suom1** [comment]
We've updated the documentation with a working solution!
