### ISSUE TITLE
wireguardctrl has been moved and renamed to wgctrl

### ISSUE THREAD

**Issue by mdlayher** [EmbarkStudios/wireguard-ui#2]
Hello, I've spotted your project as a user of my wireguardctrl project and wanted to reach out to let you know that the project has been moved to the WireGuard org and the main package has been renamed:

https://godoc.org/golang.zx2c4.com/wireguard/wgctrl

It should be fairly easy to update, but feel free to reach out if you run into any issues. Thanks!

**Comment by dln** [comment]
All good, fixed and currently looking into WireGuard/wgctrl-go/issues/64 ... :+1:
