### ISSUE TITLE
Can't create new profile

### ISSUE THREAD

**Issue by FinlayDaG33k** [EmbarkStudios/wireguard-ui#20]
When I install wireguard-ui and click the "+" button in the UI (while logged in as `anonymous`, because I can't find a login button nor any credentials to use), nothing happens (the network inspector shows a `401 Unauthorized`).  
In the console on the server I get:
```
time="2019-12-12T00:38:59Z" level=debug msg="Google auth enabled"
time="2019-12-12T00:38:59Z" level=error msg="Token not found"
```

Looking through the code a bit, I can find the following change:
https://github.com/EmbarkStudios/wireguard-ui/pull/19/files#diff-34c6b408d72845d076d47126c29948d1R37

Interestingly enough, this is a draft pull but it's already in the container?  
And I can't seem to disable this since `--google-auth=false` throws the error:
```
wireguard-ui: error: unexpected false, try --help
```

I've dug a bit deeper and saw that the `latest` docker image (which is used by default when using the command in the `README.md` is causing this issue.  
Downgrading to `v1.0.0` solves this issue and causes the bug in #10, which is fine (since I can just disable debug logging).  

I think it might be a good idea to change the command in the `README.md` don't you think?

**Comment by freddd** [comment]
Hi @FinlayDaG33k

For some reason it seems a PR has been pushed. I will fix this during the day. If you want to disable the google auth you have to use `--no-google-auth` as that is how the library we are using (kingpin) handles negative flags (https://github.com/alecthomas/kingpin#boolean-values). 

Sorry for the inconvenience and yes we should definitely update the README, though the draft should not have been pushed. I will ping you once it's fixed.

**Comment by freddd** [comment]
Hi again @FinlayDaG33k,

PR's are no longer published and the `latest` should now be pointing at master and not the draft PR (I have verified it locally). Sorry again for the inconvenience. I will close the issue, feel free to reopen it if you notice the issue still being present.

**Comment by FinlayDaG33k** [comment]
@freddd sweet :>
