### ISSUE TITLE
docker image fail

### ISSUE THREAD

**Issue by alexanderek** [EmbarkStudios/wireguard-ui#4]
Hi,

I get an error when trying pull image. `docker pull embarkstudios/wireguard-ui`

`Error response from daemon: mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not '`

**Comment by lsjostro** [comment]
```

**Comment by dln** [comment]
Yeah, it looked like it's docker being unhappy with OCI images. I added the format flag to buildah, and now docker seems happy. :+1:

**Comment by timothymiller** [comment]
I am experiencing the same issue. @dln Can you elaborate on how you resolved the issue?

**Comment by dln** [comment]
@timothymiller what I did was change buildah to use docker format of the manifest. For me, this seems to do the trick for docker pull.

I only tested pulling and running with docker 19.03-ce on Arch and docker 18.09 on Ubuntu Bionic though.

Is it still borking on other/older versions perhaps?
