### ISSUE TITLE
Would it be possible for a non-Docker version of WireGuard-UI ?

### ISSUE THREAD

**Issue by bmullan** [EmbarkStudios/wireguard-ui#5]
I have been looking for a Web GUI for WIreGuard and saw EmbarkStudio's WireGuard-UI but we would need a non-Docker version?

thanks for any info

**Comment by dln** [comment]
Absolutely! I'll add a plain binary build to the pipeline and we can add them as artifacts on the Releases page?
I'd like to have arm7 binaries (and container images) in places as well for use on raspberry pi, which could be pretty useful.
But let's start with cutting a first release :)

**Comment by dln** [comment]
I made a first release with a linux-amd64 binary attached. Enjoy!

https://github.com/EmbarkStudios/wireguard-ui/releases/tag/v1.0.0

**Comment by bmullan** [comment]
@dln 

Daniel

Thanks I'll give it a try next week.

Just FYI but [you might want to change the following](All wireguard-ui images are at:
https://hub.docker.com/r/embarkstudios/wireguard-ui/tags) to say "**_All Docker WireGuard-UI images are at:_**"  instead of "All WireGuard-UI images are at:"

> All wireguard-ui images are at:
> https://hub.docker.com/r/embarkstudios/wireguard-ui/tags
