### ISSUE TITLE
Unable to run container on Unraid

### ISSUE THREAD

**Issue by hoveeman** [EmbarkStudios/wireguard-ui#8]
I'm trying to run the container on my Unraid 6.7.2 server but am receiving the following error. Please let me know what else I can provide. I appreciate the help!

```
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='Wireguard-UI' --net='bridge' --privileged=true -e TZ="America/New_York" -e HOST_OS="Unraid" -p '18080:8080/tcp' -p '5555:5555/tcp' -v '/mnt/cache/appdata/wireguard-ui':'/data':'rw' 'embarkstudios/wireguard-ui' --data-dir=/data --log-level=debug
37ff59c0d2a1a224db44c4f56ec3b2c6f7c244380c4579deedce7199840169dc
/usr/bin/docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: "/bin/sh": stat /bin/sh: no such file or directory": unknown.

The command failed.
```

**Comment by djarbz** [comment]
I am getting this error as well, running on Ubuntu.
Linux dev 4.15.0-30-generic #32-Ubuntu SMP Thu Jul 26 17:42:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Docker version 19.03.3, build a872fc2f86

**Comment by TheWiresharkGuy** [comment]
Same error as well on Arch

**Comment by djarbz** [comment]
I got it to work by running
`docker run --rm -it --privileged --entrypoint "/wireguard-ui" -v /tmp/wireguard-ui:/data -p 8080:8080 -p 5555:5555 embarkstudios/wireguard-ui --data-dir=/data --log-level=debug`
Looks like there is an issue with the entrypoint.

**Comment by G3rb3r** [comment]
under Debian 10 it doesn't work like this either
`docker run --rm -it --privileged --entrypoint "/wireguard-ui" -v /tmp/wireguard-ui:/data -p 8080:8080 -p 5555:5555 embarkstudios/wireguard-ui --data-dir=/data --log-level=debug
INFO[0000] Starting
DEBU[0000] ipAddr: 172.72.72.1  ipNet: 172.72.72.0/24
DEBU[0000] Read server config from file: /data/config.json
DEBU[0000] Configuration loaded with public key: FKWrHlKTXH4OrgEYKavCI9vHOZhI39ZspjcqQvTa8h4=
DEBU[0000] Server initialized: /data
INFO[0000] Enabling sys.net.ipv4.ip_forward
DEBU[0000] Adding wireguard device: wg0
FATA[0000] operation not supported
`

**Comment by djarbz** [comment]
@G3rb3r looks like you are running into a different issue, the container is starting, which is the OP's issue. Looks like for some reason it cannot create the wg interface, I ran into this on my GCE instance and haven't had time to dig into it further. I would suggest raising a separate issue for this error.

**Comment by suom1** [comment]
Thank you @djarbz for the solution. I will now close this case, and I have updated README!
